version: '3.7'

services:

  fit-calendar-frontend:
    container_name: fit-calendar-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - '80:80'

  fit-calendar-api:
    container_name: fit-calendar-api
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - '3000:3000'

